### PR TITLE
FAPI 0.86.1 sync

### LINKED ISSUE #109: Terrain does not load after entering the Nether
After entering the Nether in the first world, then leaving and joining the second world (with never generated Nether), entering the Nether results in no terrain loading. After leaving and joining the second world, the structures that were supposed to be generated within render distance are not.

OS: Linux
Java: 17.0.7
Minecraft: 1.20.1
Quilt Loader: 0.19.2
Quilted Fabric API: 7.0.6

Steps to reproduce:
1. Create new world
2. Enter the nether (it loads normally)
3. Leave world
4. Create second new world
5. Enter the nether
6. Terrain not loading, and log spams with:
```
[Render thread/ERROR]: Error executing task on Client
java.lang.IllegalArgumentException: No value with id -1
	at net.minecraft.class_2359.method_39974(class_2359.java:19) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_2834.method_12289(class_2834.java:82) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_2841.method_12326(class_2841.java:174) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_2826.method_12258(class_2826.java:159) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_2818.method_12224(class_2818.java:456) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_631.method_16020(class_631.java:117) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_634.method_38539(class_634.java:773) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_634.method_11128(class_634.java:738) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_2672.method_11528(class_2672.java:45) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_2672.method_11054(class_2672.java:12) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_310.method_1523(class_310.java:1175) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524) ~[quilt-loader-0.19.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82) ~[quilt-loader-0.19.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.19.2.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
```

Full crash log: https://mclo.gs/Q6ybvpK

### LINKED ISSUE #112: QFAPI does not make `Blocks.createLogBlock` public - buildscript update required.
Title says it all, really.
`__maximum__` on the ModFest Discord says:
> Ok yeah quilted fabric API needs to update to latest fabric API's new buildscript changes

That's really all there is to say on the matter

### LINKED ISSUE #113: Crash with Continuity
The client won't start with this enabled, because Continuity requires a newer version of the Fabric API. Is a sync with the latest Fabric API, which should solve this issue, already in work?

### PR DESCRIPTION
**Pull request by rinOfTheStars**
Is _seemingly_ mostly functional, but there's a chance I missed something somewhere, and this port also requires extensive testing against FAPI 0.86.0, current QSL, and vanilla for the recently added FAPI Dynamic Registries.

The other changes, including the new Fabric Model Loading API and small additions to the Fabric Transfer API, are seemingly drag-and-drop and did not require significant edits to make functional.

### CODE REVIEW

File: fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/SerializableRegistriesMixin.java [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+	private static Stream<DynamicRegistryManager.Entry<?>> stream(DynamicRegistryManager dynamicRegistryManager) {
+		return null;
+	}
+
+	@Dynamic("method_45961: Codec.xmap in createDynamicRegistryManagerCodec")
+	@Redirect(method = "method_45961", at = @At(value = "INVOKE", target = "Lnet/minecraft/registry/SerializableRegistries;stream(Lnet/minecraft/registry/DynamicRegistryManager;)Ljava/util/stream/Stream;"))
+	private static Stream<DynamicRegistryManager.Entry<?>> filterNonSyncedEntries(DynamicRegistryManager drm) {
+		return stream(drm).filter(entry -> {
+			//boolean canSkip = DynamicRegistriesImpl.SKIP_EMPTY_SYNC_REGISTRIES.contains(entry.key());
+			//return !canSkip || entry.value().size() > 0;
```
Comment (eristhea) [inline fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/SerializableRegistriesMixin.java]: maybe a comment explaining this? the bridge seems very solid though!

File: fabric-registry-sync-v0/src/testmod/java/net/fabricmc/fabric/test/registry/sync/RegistrySyncTest.java [hunk 2]
```diff
@@ -106,9 +106,9 @@ public void onInitialize() {
 
 		// Vanilla status effects don't have an entry for the int id 0, test we can handle this.
 		RegistryAttributeHolder.get(Registries.STATUS_EFFECT).addAttribute(RegistryAttribute.MODDED);
-		Registry.register(Registries.STATUS_EFFECT, new Identifier("test", "status_effect"),
-				StatusEffectAccessor.createNewStatusEffect(StatusEffectCategory.NEUTRAL, 0xffff9900)
-		);
+		//Registry.register(Registries.STATUS_EFFECT, new Identifier("test", "status_effect"),
```
Comment (eristhea) [inline fabric-registry-sync-v0/src/testmod/java/net/fabricmc/fabric/test/registry/sync/RegistrySyncTest.java]: why?

**Review by eristhea — COMMENTED** [review]
thank you so much for this! as far as I can tell the dynamic registry api is unused in mods so can't really be tested, but this port looks good

File: fabric-registry-sync-v0/src/testmod/java/net/fabricmc/fabric/test/registry/sync/RegistrySyncTest.java (hunk 2 above)
Comment (rinOfTheStars) [reply fabric-registry-sync-v0/src/testmod/java/net/fabricmc/fabric/test/registry/sync/RegistrySyncTest.java]: I'm looking at it now and I have no clue why that happened—my guess is the checkstyle autoapplier did it? I'll revert it in a bit.

Comment (rinOfTheStars) [reply fabric-registry-sync-v0/src/testmod/java/net/fabricmc/fabric/test/registry/sync/RegistrySyncTest.java]: Fixed as of latest commit (80ec887)

File: fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/SerializableRegistriesMixin.java (hunk 1 above)
Comment (rinOfTheStars) [reply fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/SerializableRegistriesMixin.java]: I'm honestly not sure if it even works as a proper bridge, mainly because the Registry Sync API is experimental and ~~undocumented~~ sparsely documented—mainly went on a hunch when writing this... 

Instead of pinging patbox I'm going to look at the Sync API impl first, see if I can figure out wtf it's doing, and then ping him if I can't

Comment (rinOfTheStars) [reply fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/SerializableRegistriesMixin.java]: Does this work as a bridge for FAPI's version of optional Dynamic Registries or will it need a fix on QSL's side to properly support? @Patbox

The full relevant code is at https://github.com/cocona20xx/quilted-fabric-api/blob/0.86.0-upstream-compat/fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/SerializableRegistriesMixin.java, since commit view is a bit annoying to actually get a look at code in.

I *think* it'll work, if I'm understanding QSL's `RegistrySynchronization#isEntryPresent` correctly, but I think it's best to actually ask you since you're the author of said API and probably know best here.

Comment (Patbox) [reply fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/SerializableRegistriesMixin.java]: Quilt's registry sync was always intended to be only used for static registries. It also uses flag system for entries. So if entry is optional, isEntryPresent will return whatever true if client has that optional entry, otherwise not

**Comment by rinOfTheStars** [comment]
Waiting on https://github.com/QuiltMC/quilt-standard-libraries/pull/329 and https://github.com/QuiltMC/quilt-standard-libraries/pull/330 to be merged and a new minor release of QSL to be released containing said fixes/additions to continue on this, as both features will heavily simply what QFAPI needs to come in sync with 0.86.0 and 0.86.1

On that subject, should QFAPI skip 0.86.0 and only provide support for 0.86.1? The latter is pretty much all bugfixes, so it seems like a reasonable thing to do, but I'm not sure.

**Comment by eristhea** [comment]
yes, we skip versions that release between updates so we'll go straight to `0.86.1`!

**Comment by rinOfTheStars** [comment]
While waiting for QSL prs 330 and 329 to be merged, going to look into fixing ~~#112~~, ~~#109~~, ~~#108~~, and possibly #69, since those aren't reliant on QSL changes
edit: 112 apparently is already fixed. guh. 
edit 2 ~ tokyo drift: Found the fix for #109, it's in https://github.com/QuiltMC/quilt-standard-libraries/pull/333
edit the third: #108 doesn't seem to actually be real in pure QSL + QFAPI, hopefully

File: deprecated/fabric-models-v0/build.gradle [hunk 3]
```diff
@@ -0,0 +1,7 @@
+archivesBaseName = "fabric-models-v0"
+version = getSubprojectVersion(project)
```
Comment (EnnuiL) [inline deprecated/fabric-models-v0/build.gradle]:
```suggestion
archivesBaseName = "quilted_fabric_models_v0"
version = getSubprojectVersion(project)
upstream_version = getSubprojectUpstreamVersion(project)
```

File: fabric-model-loading-api-v1/src/client/resources/quilt.mod.json [hunk 4]
```diff
@@ -0,0 +1,50 @@
...
+	"fabric-api:module-lifecycle": "stable",
+	"modmenu": {
+		"badges": [
+			"library"
+		],
+		"parent": "quilted_fabric_api"
+	},
+	"quilt_loom": {
+		"injected_interfaces": {
+			"net/minecraft/class_1092": [ "net/fabricmc/fabric/api/client/model/loading/v1/FabricBakedModelManager" ]
```
Comment (EnnuiL) [inline fabric-model-loading-api-v1/src/client/resources/quilt.mod.json]:
```suggestion
			"net/minecraft/class_1092": ["net/fabricmc/fabric/api/client/model/loading/v1/FabricBakedModelManager"]
```

File: fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/api/event/registry/DynamicRegistries.java [hunk 5]
```diff
@@ -0,0 +1,159 @@
...
+import net.minecraft.registry.RegistryKey;
+import net.minecraft.registry.RegistryLoader;
+
+import net.fabricmc.fabric.impl.registry.sync.DynamicRegistriesImpl;
+
+/**
+ *
+ * @deprecated Use Quilt Registry API's {@link org.quiltmc.qsl.registry.api.dynamic.DynamicMetaRegistry} instead.
+ *
+ * <p>Contains methods for registering and accessing dynamic {@linkplain Registry registries}.
```
Comment (EnnuiL) [inline fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/api/event/registry/DynamicRegistries.java]: Actually, instead of doing this (which breaks Fabric's checkstyle check):
```suggestion
 * Contains methods for registering and accessing dynamic {@linkplain Registry registries}.
```

File: fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/api/event/registry/DynamicRegistries.java [hunk 6]
```diff
@@ -0,0 +1,159 @@
...
+ *
+ * // Option 2a: Register a synced registry
+ * // @link substring=registerSynced target="#registerSynced(RegistryKey, Codec, SyncOption...)":
+ * DynamicRegistries.registerSynced(MY_DATA_KEY, MyData.CODEC);
+ *
+ * // Option 2b: Register a synced registry with a different network codec
+ * // @link substring=registerSynced target="#registerSynced(RegistryKey, Codec, Codec, SyncOption...)":
+ * DynamicRegistries.registerSynced(MY_DATA_KEY, MyData.CODEC, MyData.NETWORK_CODEC);
+ * }
+ */
```
Comment (EnnuiL) [inline fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/api/event/registry/DynamicRegistries.java]: I'd do this
```suggestion
 * }
 *
 * @deprecated Use Quilt Registry API's {@link org.quiltmc.qsl.registry.api.dynamic.DynamicMetaRegistry} instead.
 */
```

File: fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/api/event/registry/DynamicRegistries.java [hunk 7]
```diff
@@ -0,0 +1,159 @@
...
+@Deprecated()
```
Comment (EnnuiL) [inline fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/api/event/registry/DynamicRegistries.java]: oh, also,
```suggestion
@Deprecated
```

File: fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/DynamicRegistriesImpl.java [hunk 8]
```diff
@@ -0,0 +1,79 @@
...
+		return List.copyOf(RegistryLoader.DYNAMIC_REGISTRIES);
+	}
+
+	public static <T> void register(RegistryKey<? extends Registry<T>> key, Codec<T> codec) {
+		Objects.requireNonNull(key, "Registry key cannot be null");
+		Objects.requireNonNull(codec, "Codec cannot be null");
+
+		if (!DYNAMIC_REGISTRY_KEYS.add(key)) {
+			throw new IllegalArgumentException("Dynamic registry " + key + " has already been registered!");
+		}
```
Comment (EnnuiL) [inline fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/DynamicRegistriesImpl.java:61]: You did say that you have more work to do; i won't poke more about the checkstyle violations; Don't forget to address them! or else it won't build

File: fabric-registry-sync-v0/src/main/resources/quilted_fabric_registry_sync_v0.mixins.json [hunk 9]
```diff
@@ -1,19 +1,22 @@
 {
   "required": true,
   "package": "net.fabricmc.fabric.mixin.registry.sync",
-  "compatibilityLevel": "JAVA_17",
+  "compatibilityLevel": "JAVA_16",
```
Comment (EnnuiL) [inline fabric-registry-sync-v0/src/main/resources/quilted_fabric_registry_sync_v0.mixins.json]: nonononono
```suggestion
  "compatibilityLevel": "JAVA_17",
```

File: fabric-registry-sync-v0/src/main/resources/quilted_fabric_registry_sync_v0.mixins.json [hunk 10]
```diff
@@ -1,19 +1,22 @@
...
     "RegistriesAccessor",
     "RegistriesMixin",
+    "SaveLoadingMixin",
+    "SerializableRegistriesMixin",
     "SimpleRegistryMixin",
-    "StructuresToConfiguredStructuresFixMixin"
+    "StructuresToConfiguredStructuresFixMixin",
+    "TagManagerLoaderMixin",
+    "quilt.DynamicRegistryManagerSetupContextImplMixin",
+    "quilt.workaround.DynamicRegistryManagerSetupContextImplMixin"
```
Comment (EnnuiL) [inline fabric-registry-sync-v0/src/main/resources/quilted_fabric_registry_sync_v0.mixins.json:16]: i don't know how to feel about the reorder; maybe i'll let it pass

File: gradle.properties [hunk 11]
```diff
@@ -3,8 +3,8 @@ org.gradle.parallel=true
 fabric.loom.multiProjectOptimisation=true
 
 archivesBaseName=quilted_fabric_api
-version=7.0.6
-upstream_version=0.85.0
+version=7.0.7
```
Comment (EnnuiL) [inline gradle.properties]: keep it 7.0.6 for now, it's a PR;
```suggestion
version=7.0.6
```
it's not going to be 7.0.7 anyway

File: src/main/resources/quilt.mod.json [hunk 12]
```diff
@@ -114,6 +114,10 @@
 				"id": "quilted_fabric_rendering_v0",
 				"optional": true
 			},
+			{
+				"id": "quilted_fabric_models_v0",
+				"optional": true
+			},
```
Comment (EnnuiL) [inline src/main/resources/quilt.mod.json:120]: once again, i wish this was alphabetically sorted; but i can address that post-merge :p

**Review by EnnuiL — CHANGES_REQUESTED** [review]
Looks like a solid upstream sync to me! (at least ignoring the fact that it has pending changes)
I did see few things that look small but that are actually important to fix, so here they are:

File: fabric-registry-sync-v0/src/main/resources/quilted_fabric_registry_sync_v0.mixins.json (hunk 9 above)
Comment (rinOfTheStars) [reply fabric-registry-sync-v0/src/main/resources/quilted_fabric_registry_sync_v0.mixins.json]: I have no clue how that got changed what the hell

File: fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/SerializableRegistriesMixin.java (hunk 1 above)
Comment (rinOfTheStars) [reply fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/SerializableRegistriesMixin.java]: Will be improved in an upcoming commit thanks to QSL changes.

**Comment by rinOfTheStars** [comment]
With the latest commit, QFAPI should be ready for testing and one final review pass! Going to set this as a ready PR now.

**Review by eristhea — APPROVED** [review]
looks great!

**Review by EnnuiL — APPROVED** [review]
