### PR TITLE
Work around the usage of unregistered entries on content registries through deferring queues

### LINKED ISSUE #31: QSL 4.0.0 beta 8 and above crashes with Artisanat
**MC** 1.19.2
**QSL** 4.0.0 beta 8 and 9
**[Artisanat](https://www.curseforge.com/minecraft/mc-mods/artifacts-fabric)** 2.3.0

Starting with beta 8, the game crashes on startup when Artisanat is installed. Initially reported there: https://github.com/DawnTeamMC/Artisanat/issues/29, but according to the dev the issue is on Quilt's side.

QSL 4.0.0 beta 7 lets the game start normally with Artisanat.

Logs: https://gist.github.com/Footage2-Amply-Pounce/fdbb31bcdcde4b1bf8a351edee369716

### PR DESCRIPTION
**Pull request by EnnuiL**
This PR fixes crashes (such as the one in #31) that involve the bad practice of using an unregistered entry on the registration of a pair in a content registry through a deferring queue system that defers those registrations to only after the relevant entries are registered.

This PR also adds the `quilted_fabric_api.quilted_fabric_content_registries_v0.crash_on_deferring_entry` property, which when enabled (by default, if it's a dev environment, it's enabled, else, disabled), will crash if a deferred queue is activated, allowing for an easier time finding out which mod was responsible for using an unregistered entry

Modders are still encouraged to fix the issue on their side, especially since the deferred queues may have a performance impact and plus, these are unregistered entries, they can and will cause trouble eventually, Quilt or not.

...oh right, github does not accept indirectness (which is fair enough); *ahem*, fixes #31

### CODE REVIEW

File: fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/impl/content/registry/util/QuiltDeferringQueues.java [hunk 1]
```diff
@@ -0,0 +1,181 @@
...
+			return QuiltDeferringQueues.BLOCK.deferEntry(entry.block());
+		} else if (value instanceof Item item) {
+			QuiltDeferringQueues.ITEM.deferEntry(item);
+		} else if (value instanceof GameEvent event) {
+			QuiltDeferringQueues.GAME_EVENT.deferEntry(event);
+		} else {
+			return false;
+		}
+
+		return true;
```
Comment (Leo40Git) [inline fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/impl/content/registry/util/QuiltDeferringQueues.java]: ...okay, the flow of this method confuses me.
```suggestion
		if (value instanceof Block block) {
			QuiltDeferringQueues.BLOCK.deferEntry(block);
			return true;
		} else if (value instanceof BlockState state) {
			QuiltDeferringQueues.BLOCK.deferEntry(state.getBlock());
			return true;
		} else if (value instanceof ReversibleBlockEntry entry) {
			return QuiltDeferringQueues.BLOCK.deferEntry(entry.block());
		} else if (value instanceof Item item) {
			QuiltDeferringQueues.ITEM.deferEntry(item);
			return true;
		} else if (value instanceof GameEvent event) {
			QuiltDeferringQueues.GAME_EVENT.deferEntry(event);
			return true;
		}

		return false;
```
This might not be DRY, but... c'mon, it's a `return primitive` statement.

File: fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/impl/content/registry/util/QuiltDeferringQueues.java [hunk 2]
```diff
@@ -0,0 +1,181 @@
...
+			}
+
+			return false;
+		}
+
+		public void activate() {
+			if (!this.active) {
+				if (CRASH_ON_DEFERRING_ENTRY.toBooleanOrElse(QuiltLoader.isDevelopmentEnvironment())) {
+					if (CRASH_ON_DEFERRING_ENTRY == TriState.DEFAULT) {
+						LOGGER.error("An unregistered entry on the " + this.registry + " registry was attempted to be registered in a content registry through the Quilted Fabric API bridge! Due to this happening on a dev environment, the game will proceed to crash now. This crash may be disabled by disabling the \"quilted_fabric_api.quilted_fabric_content_registries_v0.crash_on_deferring_entry\" property.");
```
Comment (Leo40Git) [inline fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/impl/content/registry/util/QuiltDeferringQueues.java]: For one thing this, and the other logger messages here, _need_ to be split into multiple lines for readability's sake.
And... how do you "disable" a property, exactly? This should be reworded to something like:
```
This crash may be disabled by setting the "quilted_fabric_api.quilted_fabric_content_registries_v0.crash_on_deferring_entry" property to "OFF".
```

**Review by Leo40Git — CHANGES_REQUESTED** [review]
The logic itself LGTM, though I have a few issues with this.
